apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce   # PostgreSQL only needs a single write
  resources:
    requests:
      storage: 5Gi     # adjust as needed
  storageClassName: juicefs
